server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false
vaadin.launch-browser=true

spring.jpa.defer-datasource-initialization = true

 # debug=true
vaadin.frontend.hotdeploy.max-bundle-size=10MB
svg.output.directory=generated_svgs
# svg.output.directory=/var/myapp/generated_svgs
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./data/svgdb

#local development
#spring.profiles.active=dev
# Base domain used for tenant URLs
app.base-domain=kjwlocal.com
app.environment=development

# API path used for all tenants
app.api-path=/api/drawing-client/recieve-svg
app.external-api-path=http://host.docker.internal
app.drawing-api-token=drawing-api-token-change-it

vaadin.allowed-packages=com.example.application
vaadin.frontend.hotdeploy=false
vaadin.productionMode=true